version: "3.9"
name: tenants

services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data-new:/var/lib/postgresql/data
    networks:
      - tenants-net

  backend:
    build: ./backend
    container_name: backend-container
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    networks:
      - tenants-net

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - tenants-net

volumes:
  postgres-data-new:

networks:
  tenants-net:
    driver: bridge
