# Generated by Django 5.2.4 on 2025-08-07 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the plan (e.g., Free, Pro, Enterprise).', max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='The monthly price of the plan.', max_digits=10)),
                ('max_users', models.PositiveIntegerField(default=1, help_text='The maximum number of users allowed under this plan.')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, help_text='The date the subscription started.')),
                ('end_date', models.DateTimeField(blank=True, help_text='The date the subscription ends. Null for ongoing subscriptions.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the subscription is currently active.')),
                ('plan', models.ForeignKey(help_text='The plan this user is subscribed to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.plan')),
                ('user', models.OneToOneField(help_text='The user who owns this subscription.', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
