# Generated by Django 5.2.4 on 2025-08-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_tenant_manager', '0002_tenant_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='subdomain',
        ),
    ]
